# app/Dockerfile

FROM public.ecr.aws/lambda/python:3.9

# Set working directory to function root directory
ARG FUNCTION_DIR="/translator_playground"


# install dependenciesWORKDIR ${FUNCTION_DIR}
COPY requirements.txt .
RUN pip3 install --requirement ${LAMBDA_TASK_ROOT}/requirements.txt

# copy the requirements file to the working directory
WORKDIR ${FUNCTION_DIR}
COPY main.py ${LAMBDA_TASK_ROOT}
COPY lambda_function.py ${LAMBDA_TASK_ROOT}
COPY requirements.txt ${LAMBDA_TASK_ROOT}
COPY tmxFileProcess.py ${LAMBDA_TASK_ROOT}
COPY bedrock_apis.py ${LAMBDA_TASK_ROOT}

EXPOSE 8501

CMD ["lambda_function.lambda_handler" ]


